const Users = [
  {
    id: "1",
    Name: "Jaycn",
    Height: "181cm",
    Weight: "80kg",
    Phone_Number: "09157379264",
    State: "Anambra",
    Religion: "Christian",
    Job: "Software Engineer",
    Position: "Intern",
  },
  {
    id: "2",
    Name: "Le buks",
    Height: "183cm",
    Weight: "95kg",
    Phone_Number: "07057270913",
    State: "Anambra",
    Religion: "Christian",
    Job: "Chemical Engineer",
    Position: "Intern",
  },
  {
    id: "3",
    Name: "Steph Chi",
    Height: "171cm",
    Weight: "65kg",
    Phone_Number: "08154165386",
    State: "Anambra",
    Religion: "Christian",
    Job: "Health Science and Dietetics Engineer",
    Position: "Intern",
  },
  {
    id: "4",
    Name: "Gavis",
    Height: "182cm",
    Weight: "75kg",
    Phone_Number: "08093575985",
    State: "Anambra",
    Religion: "Christian",
    Job: "Politician",
    Position: "Intern",
  },
  {
    id: "5",
    Name: "Kash",
    Height: "191cm",
    Weight: "93kg",
    Phone_Number: "08047927536",
    State: "Imo",
    Religion: "Christian",
    Job: "Web developer",
    Position: "Intern",
  },
];
export default Users;
